### ISSUE TITLE
Lose track of subject 

### ISSUE THREAD

**Issue by araujokth** [KumarRobotics/motion_capture_system#2]
Hi,

Thanks for sharing! I am using your code to get the data from the qualisys mocap and many times I get the output "[ WARN] [1450178660.490998011]: Lose track of subject crazyflie" even though the mocap still outputs the correct values all the time, from what I can see. I was wondering if there was anything I could do regarding this issue?

Also, when setting up the parameters in qualisys.launch, I choose port "22223" but for some reason, it is displayed port 22222 when running the code as 

"[ INFO] [1450179306.041624629]: Connecting to the Qualisys at: IP_ADDRESS:22222
QTM RT Interface connected
Version set to 1.7". If I try to change the value   nh.param("server_base_port", base_port, 22222); in the QualisysDriver.cpp, to 22223 then I cannot connect to the mocap system.

Another question, is it that the default measurements are 6DOF with Euler angles?

I am running ROS Jade on Ubuntu 14.04 and I am using a crazyflie quadrotor.

Thanks for the help!

**Comment by ke-sun** [comment]
Hi, 

Sorry for the late reply.
1. I think the warnings is because there are really some frames that are lost. Note that for every lost frame, the driver will post a warning saying lose track of the object. For situations like a single frame lost, it may not directly reflected on mocap software provided by qualisys, but it will generate a warning by the driver. Given the size of a crazyfile, I think it is not uncommon to lose a few frames per sec. I suggest you use "rostopic hz" to check the actual frequency that the driver publishes, and see if you can tolerate with that. 
2. That is actually a bug. You can change "base_port" to "server_base_port" in qualisys.launch for the moment. Then you can specify the base port in the launch file. I will fix the software tmr.
3. I am not sure of this. I think the port is with the software provided by qualisys, which specifies to and from which process, the msgs should be routed. It is not decided on the driver side.
4. The driver publishes msgs of type nav_msgs/Odometry, which contains 6DOF with quaternion. 

Hope that helps.
